PROJECT = cowboy_php_hello
PROJECT_DESCRIPTION = Sample PHP Project for Cowboy
PROJECT_VERSION = 0.1.0

DEPS = cowboy_fcgi
dep_cowboy_fcgi = git https://github.com/unix1/cowboy_fcgi

include ../../erlang.mk
